BookHarbor/E-Commerce/Areas/Admin/Controllers/BookController.cs
using BookHarbor.Core.Services.Interface;
using E_commerce.Data.Repository.IRepository;
using E_commerce.Models.Models;
using E_commerce.Models.ViewModels;
using E_commerce.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;

namespace E_Commerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class BookController : Controller
    {
        private readonly IUnitOfWork _db;
        private readonly IWebHostEnvironment _webEnvironment;
        private readonly IBookService _bookService;
        public BookController(IUnitOfWork db, IWebHostEnvironment webEnvironment, IBookService bookService)
        {
            _db = db;
            _webEnvironment = webEnvironment;
            _bookService = bookService;
        }

        public IActionResult Index()
        {
            var getAll = _db.Book.GetAll(includeProperties:"Genre").ToList();
            
            return View(getAll);
        }

        //public IActionResult Upsert(int? id)
        //{
        //    BookViewModels productVm = new()
        //    {
        //        GenreList = _db.Genre.GetAll()
        //        .Select(x => new SelectListItem
        //        {
        //            Text = x.Name,
        //            Value = x.Id.ToString()
        //        }),
        //        Book = new Book()
        //    };
        //    if (id==null || id==0)
        //    {
        //        //Create
        //        return View(productVm);
        //    }
        //    else
        //    {
        //        //Update
        //        productVm.Book = _db.Book.Get(x=>x.Id==id);
        //        return View(productVm);
        //    }            
        //}

        public IActionResult Upsert(int? id)
        {
            BookViewModels productVm;

            if (id == null || id == 0)
            {
                productVm = _bookService.CreateNewBookViewModel();
            }
            else
            {
                productVm = _bookService.GetBookViewModel(id);
            }

            return View(productVm);
        }




        //[HttpPost]
        //public IActionResult Upsert(BookViewModels category, IFormFile? file)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        string wwwRootPath = _webEnvironment.WebRootPath;
        //        if (file != null)
        //        {
        //            string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
        //            string productPath =Path.Combine(wwwRootPath, @"images\product");

        //            if (!string.IsNullOrEmpty(category.Book.ImageUrl))
        //            {
        //                //delete the old image
        //                var oldImagePath = 
        //                    Path.Combine(wwwRootPath, category.Book.ImageUrl.TrimStart('\\'));
        //                if (System.IO.File.Exists(oldImagePath))
        //                {
        //                    System.IO.File.Delete(oldImagePath);
        //                }
        //            }

        //            using (var filestream = new FileStream(Path.Combine(productPath,fileName),FileMode.Create))
        //            {
        //                file.CopyTo(filestream);
        //            }
        //            category.Book.ImageUrl = @"\images\product\" + fileName;
        //        }

        //        if (category.Book.Id==0)
        //        {
        //            _db.Book.Add(category.Book);
        //        }
        //        else
        //        {
        //            _db.Book.Update(category.Book);
        //        }


        //        _db.Save();
        //        TempData["Success"] = "Book created successfully";
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        category.GenreList = _db.Genre.GetAll()
        //       .Select(x => new SelectListItem
        //       {
        //           Text = x.Name,
        //           Value = x.Id.ToString()
        //       });
        //        return View(category);
        //    }


        //}

        //public IActionResult Delete(int Id)
        //{
        //    if (Id == null || Id == 0)
        //    {
        //        return NotFound();
        //    }
        //    var category = _db.Book.Get(c => c.Id == Id);
        //    if (category == null)
        //    {
        //        return BadRequest();
        //    }
        //    return View(category);
        //}
        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeletePost(int Id)
        //{
        //    var category = _db.Book.Get(x => x.Id == Id);
        //    if (category == null)
        //    {
        //        return NotFound();
        //    }
        //    _db.Book.Remove(category);
        //    _db.Save();
        //    TempData["Success"] = "Book Deleted successfully";
        //    return RedirectToAction("Index");

        //}

        [HttpPost]
        public IActionResult Upsert(BookViewModels books, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string imagePath = _bookService.UploadBookImage(file);
                    if (!string.IsNullOrEmpty(books.Book.ImageUrl))
                    {
                        _bookService.DeleteBookImage(books.Book.ImageUrl);
                    }
                    books.Book.ImageUrl = imagePath;
                }

                if (books.Book.Id == 0)
                {
                    _bookService.AddBook(books.Book);
                }
                else
                {
                    _bookService.UpdateBook(books.Book);
                }

                TempData["Success"] = "Book created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                books.GenreList = _db.Genre.GetAll()
                    .Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });
                return View(books);
            }
        }



        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var getAll = _db.Book.GetAll(includeProperties: "Genre").ToList();
            return Json(new
            {
                data = getAll
            });
        } 
        
        [HttpDelete]
        public IActionResult Delete(int Id)
        {
            var productToBeDeleted = _db.Book.Get(x => x.Id == Id);
            if (productToBeDeleted == null)
            {
                return Json(new {success = false, message = "Error while deleting"});
            }
            var oldImagePath =
                           Path.Combine(_webEnvironment.WebRootPath,
                           productToBeDeleted.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _db.Book.Remove(productToBeDeleted);
            _db.Save();

            return Json(new
            {
                success = true, message ="Deleted successfully"
            });
        }


        #endregion
    }
}

BookHarbor/E-Commerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookHarbor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookHarbor.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css"/>
    <style> 
        .footers{
            position:absolute;
            bottom:0;
            width:100%;
            height:2rem;
            color:"white"
        }
      
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookHarbor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management 
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item " asp-area="Admin" asp-controller="Genre" asp-action="Index">Genre</a>
                                    </li> 
                                    <li class="nav-item">
                                        <a class="dropdown-item " asp-area="Admin" asp-controller="Book" asp-action="Index">Book</a>
                                    </li>                              
                                    <li><hr class="dropdown-divider"></li>                               
                                </ul>
                            </li>
                        }

                    </ul>
                   @* <input placeholder="Search Term..." type="text" name="text" class="input">*@
                    <div class="searchBox">

                        <input class="searchInput" type="text" name="" placeholder="Search something">
                        <button class="searchButton" href="#">



                            <svg xmlns="http://www.w3.org/2000/svg" width="29" height="29" viewBox="0 0 29 29" fill="none">
                                <g clip-path="url(#clip0_2_17)">
                                    <g filter="url(#filter0_d_2_17)">
                                        <path d="M23.7953 23.9182L19.0585 19.1814M19.0585 19.1814C19.8188 18.4211 20.4219 17.5185 20.8333 16.5251C21.2448 15.5318 21.4566 14.4671 21.4566 13.3919C21.4566 12.3167 21.2448 11.252 20.8333 10.2587C20.4219 9.2653 19.8188 8.36271 19.0585 7.60242C18.2982 6.84214 17.3956 6.23905 16.4022 5.82759C15.4089 5.41612 14.3442 5.20435 13.269 5.20435C12.1938 5.20435 11.1291 5.41612 10.1358 5.82759C9.1424 6.23905 8.23981 6.84214 7.47953 7.60242C5.94407 9.13789 5.08145 11.2204 5.08145 13.3919C5.08145 15.5634 5.94407 17.6459 7.47953 19.1814C9.01499 20.7168 11.0975 21.5794 13.269 21.5794C15.4405 21.5794 17.523 20.7168 19.0585 19.1814Z" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" shape-rendering="crispEdges"></path>
                                    </g>
                                </g>
                                <defs>
                                    <filter id="filter0_d_2_17" x="-0.418549" y="3.70435" width="29.7139" height="29.7139" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                                        <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
                                        <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"></feColorMatrix>
                                        <feOffset dy="4"></feOffset>
                                        <feGaussianBlur stdDeviation="2"></feGaussianBlur>
                                        <feComposite in2="hardAlpha" operator="out"></feComposite>
                                        <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"></feColorMatrix>
                                        <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2_17"></feBlend>
                                        <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2_17" result="shape"></feBlend>
                                    </filter>
                                    <clipPath id="clip0_2_17">
                                        <rect width="28.0702" height="28.0702" fill="white" transform="translate(0.403503 0.526367)"></rect>
                                    </clipPath>
                                </defs>
                            </svg>


                        </button>
                    </div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container mb-5">
        <main role="main" class="pb-3">
            <partial name="_notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-secondary-subtle text-muted footers ">
        <div class="text-center text-secondary footer-text">
            Made with <i class="bi bi-balloon-heart-fill"></i> by ETINOSA
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/xy98bdsq4pkt688vbfz649u9x11r88kx6rtdl699ya0r141r/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookHarbor/E-Commerce/Views/Shared/_notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib//jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
       <script type="text/javascript">
            toastr.success('@TempData["success"]');
       </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib//jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]');
    </script>
}