BookHarbor/E-Commerce/Areas/Admin/Controllers/GenreController.cs
using E_commerce.Data.Repository.IRepository;
using E_commerce.Utility;
using E_Commerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class GenreController : Controller
    {
        private readonly IUnitOfWork _db;

        public GenreController(IUnitOfWork db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var getAll = _db.Genre.GetAll().ToList();
            return View(getAll);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Genre category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "name and displayorder cannot match.");
            }
            if (ModelState.IsValid)
            {
                _db.Genre.Add(category);
                _db.Save();
                TempData["Success"] = "Genre created successfully";
                return RedirectToAction("Index");
            }
            return View();

        }
        public IActionResult Edit(int Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var category = _db.Genre.Get(c => c.Id == Id);
            if (category == null)
            {
                return BadRequest();
            }
            return View(category);
        }
        [HttpPost]
        public IActionResult Edit(Genre category)
        {

            if (ModelState.IsValid)
            {
                _db.Genre.Update(category);
                _db.Save();
                TempData["Success"] = "Genre Updated successfully";
                return RedirectToAction("Index");
            }
            return View();

        }
        public IActionResult Delete(int Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var category = _db.Genre.Get(c => c.Id == Id);
            if (category == null)
            {
                return BadRequest();
            }
            return View(category);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int Id)
        {
            var category = _db.Genre.Get(x => x.Id == Id);
            if (category == null)
            {
                return NotFound();
            }
            _db.Genre.Remove(category);
            _db.Save();
            TempData["Success"] = "Genre Deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

BookHarbor/E-Commerce/Areas/Admin/Views/Genre/Create.cshtml
@model Genre

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient mt-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Genre</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3">
                @* <div asp-validation-summary="ModelOnly"></div>*@
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" class="form-control border-0 shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayOrder" class="form-control border-0 shadow"/>
                    <label asp-for="DisplayOrder" class="ms-2" > </label>
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control"> Create</button>
                    </div>

                    <div class="col-6 col-md-3">
                        <a asp-controller="Genre" asp-action="Index" class="btn btn-outline-primary border form-control">
                            Back to list
                        </a>

                    </div>
                </div>

            </div>
        </form>
    </div>
</div>



@section Scripts
{   @{
    <partial name="_ValidationScriptsPartial"/>
}

}

BookHarbor/E-Commerce/Areas/Admin/Views/Genre/Delete.cshtml
@model Genre

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient mt-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Genre</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">               
                @*
                <div asp-validation-summary="ModelOnly"></div>*@
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" disabled class="form-control border-0 shadow" />
                    <label asp-for="Name" class="ms-2"></label>                    
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayOrder" disabled class="form-control border-0 shadow" />
                    <label asp-for="DisplayOrder" class="ms-2"> </label>                   
                </div>
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control"> Delete</button>
                    </div>

                    <div class="col-6 col-md-3">
                        <a asp-controller="Genre" asp-action="Index" class="btn btn-secondary border form-control">
                            Back to list
                        </a>

                    </div>
                </div>

            </div>
        </form>
    </div>
</div>

BookHarbor/E-Commerce/Areas/Admin/Views/Genre/Edit.cshtml
@model Genre

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient mt-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Edit Genre</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            @*  <input asp-for="Id" hidden/>*@
            <div class="border p-3 mt-4">               
                @*<div asp-validation-summary="ModelOnly"></div>*@
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" class="form-control border-0 shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayOrder" class="form-control border-0 shadow" />
                    <label asp-for="DisplayOrder" class="ms-2"> </label>
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                </div>
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control"> Update</button>
                    </div>

                    <div class="col-6 col-md-3">
                        <a asp-controller="Genre" asp-action="Index" class="btn btn-secondary border form-control">
                            Back to list
                        </a>

                    </div>
                </div>

            </div>
        </form>
    </div>
</div>




@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

BookHarbor/E-Commerce/Areas/Admin/Views/Genre/Index.cshtml
@model List<Genre>

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient mt-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Genre List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pt-4">
            <div class="col-6">
            </div>
            <div class="col-6 text-end pb-3">
                <a asp-controller="Genre" asp-action="Create" class="btn btn-primary">
                    <i class="bi bi-patch-plus-fill"></i> Create New Genre
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Genre Name
                    </th>
                    <th>
                        Display Order
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model.OrderBy(u => u.DisplayOrder))
                {
                    <tr>
                        <td>@obj.Name</td>
                        <td>@obj.DisplayOrder</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Genre" asp-action="Edit" asp-route-Id="@obj.Id" class="btn btn-primary mx-2">
                                    <i class="bi bi-pencil-square"></i>Edit
                                </a>
                                <a asp-controller="Genre" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash"></i>Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>